import DS from 'ember-data';

export default DS.Model.extend({
  title: DS.attr(),
  status: DS.attr(),
  type: DS.attr(),
  author: DS.attr(),
//  author: DS.belongsTo('user'),
  content: DS.attr(),
  parent: DS.attr(),
  link: DS.attr(),
  date: DS.attr('date'),
  modified: DS.attr('date'),
  format: DS.attr(),
  slug: DS.attr(),
  guid: DS.attr(),
  excerpt: DS.attr(),
  menu_order: DS.attr('number'),
  comment_status: DS.attr(),
  ping_status: DS.attr(),
  sticky: DS.attr('boolean'),
  date_tz: DS.attr(),
  date_gmt: DS.attr('date'),
  modified_tz: DS.attr(),
  modified_gmt: DS.attr('date'),
  featured_image: DS.attr(),
  tags: DS.hasMany('tag'),
  categories: DS.hasMany('category')
});
/*
  author: DS.belongsTo('user'),
  comment_status: DS.attr(),
  content: DS.attr(),
  date: DS.attr('date'),
  date_gmt: DS.attr('date'),
  date_tz: DS.attr(),
  excerpt: DS.attr(),
  featured_image: DS.attr(),
  format: DS.attr(),
  guid: DS.attr(),
  link: DS.attr(),
  menu_order: DS.attr('number'),
  meta: DS.hasMany('link'),
  meta: DS.attr(),
  modified: DS.attr('date'),
  modified_gmt: DS.attr('date'),
  modified_tz: DS.attr(),
  parent: DS.attr(),
  ping_status: DS.attr(),
  slug: DS.attr(),
  status: DS.attr(),
  sticky: DS.attr('boolean'),
  terms: DS.hasMany('category'),
  terms: DS.attr(),
  title: DS.attr(),
  type: DS.attr()

*/